benchmark:
	g++ -std=c++17 -O3 -o benchmark benchmark.cpp -lgmp

modular:
	g++ -std=c++17 -o modular_example modular_example.cpp

monomial:
	g++ -std=c++17 -o monomial_example monomial_example.cpp

polynomial:
	g++ -std=c++17 -o polynomial_example polynomial_example.cpp

ideal:
	g++ -std=c++17 -o ideal_example ideal_example.cpp

algo:
	g++ -std=c++17 -o algo_example algo_example.cpp -lgmp

io:
	g++ -std=c++17 -o io_example io_example.cpp -lgmp

clear:
	rm -rf benchmark modular_example monomial_example polynomial_example ideal_example algo_example io_example
